### ISSUE TITLE
Shall noline offer a way to print lines while readlining?

### ISSUE THREAD

**Issue by vi** [rustne-kretser/noline#10]
Shall it be possible to build chat-like UI where CLI app may display events while waiting for user input? Or to implement a tool like [`rlwrap(1)`](https://github.com/hanslub42/rlwrap)?

This requires at least triggering a redraw of the prompt and the buffer, so cannot be easily done without noline's support.

"Half duplex" mode of interaction with user seem to plague many readline-like libraries for Rust.

**Comment by eivindbergem** [comment]
What you describe sounds difficult at the moment, but certainly possible with some modifications to to Noline. Noline lacks functionality to restore the line editor to support other output being printed while editing a line.

Just so that I understand you correctly, you want to implement a chat client with messages appearing above the prompt:

```
me: This is a message.
other-user: No it's not.
> Yes, it is!
```

If a new message is to come in while still editing, it would have to clear the current line, print the new message, re-print the prompt and the line being edited, and finally move the cursor to wherever it was (if not at the end of the line):

```
me: This is a message.
other-user: No it's not.
other-user: Nevermind, you're right.
> Yes, it is!
```

What's lacking from newline at the moment is functionality to pausing and restoring line editing.

**Comment by Diggsey** [comment]
@eivindbergem did this get implemented?
